# Generated by Django 5.2.17 on 2026-10-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastro", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Criterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                (
                    "apoio",
                    models.CharField(
                        blank=True,
                        help_text="Texto de apoio impresso na ficha.",
                        max_length=200,
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField()),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="criterios_banca",
                        to="cadastro.edicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "critério",
                "ordering": ["edicao", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Jurado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurados",
                        to="cadastro.edicao",
                    ),
                ),
                (
                    "turmas",
                    models.ManyToManyField(
                        help_text="Turmas que o jurado avalia.",
                        related_name="jurados",
                        to="cadastro.turma",
                    ),
                ),
            ],
            options={
                "ordering": ["edicao", "nome"],
                "permissions": [
                    ("imprimir_ficha", "Pode imprimir a ficha da banca"),
                    ("concluir_conferencia", "Pode concluir a conferência da banca"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digitado_em", models.DateTimeField(auto_now_add=True)),
                ("alterado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "digitado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacoes_banca",
                        to="cadastro.projeto",
                    ),
                ),
                (
                    "jurado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacoes",
                        to="banca.jurado",
                    ),
                ),
            ],
            options={
                "verbose_name": "avaliação",
                "verbose_name_plural": "avaliações",
            },
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="banca.avaliacao",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas",
                        to="banca.criterio",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="criterio",
            constraint=models.UniqueConstraint(
                fields=("edicao", "nome"), name="criterio_nome_unico_na_edicao"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterio",
            constraint=models.UniqueConstraint(
                fields=("edicao", "ordem"), name="criterio_ordem_unica_na_edicao"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterio",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordem__gte", 1)), name="criterio_ordem_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="jurado",
            constraint=models.UniqueConstraint(
                fields=("edicao", "nome"), name="jurado_nome_unico_na_edicao"
            ),
        ),
        migrations.AddConstraint(
            model_name="avaliacao",
            constraint=models.UniqueConstraint(
                fields=("jurado", "projeto"),
                name="avaliacao_unica_por_jurado_e_projeto",
                violation_error_message="Esta ficha já foi digitada; edite a existente.",
            ),
        ),
        migrations.AddConstraint(
            model_name="nota",
            constraint=models.UniqueConstraint(
                fields=("avaliacao", "criterio"),
                name="nota_unica_por_avaliacao_e_criterio",
            ),
        ),
        migrations.AddConstraint(
            model_name="nota",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gte", 0), ("valor__lte", 10)),
                name="nota_entre_0_e_10",
            ),
        ),
    ]
