# Generated by Django 5.2.17 on 2026-10-02 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ativa', models.BooleanField(default=True)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estacoes', to='cadastro.edicao')),
            ],
            options={
                'verbose_name': 'estação',
                'verbose_name_plural': 'estações',
                'db_table': 'estacoes',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='votacao.estacao')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('consentimento_em', models.DateTimeField()),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitantes', to='cadastro.edicao')),
            ],
            options={
                'db_table': 'visitantes',
                'constraints': [models.CheckConstraint(condition=models.Q(('consentimento_em', models.Func(models.Value('hour'), models.F('consentimento_em'), function='date_trunc', output_field=models.DateTimeField()))), name='consentimento_truncado_na_hora'), models.CheckConstraint(condition=models.Q(('telefone__regex', '^[0-9]{10,13}$')), name='telefone_so_digitos')],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='cadastro.projeto')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='votacao.token')),
            ],
            options={
                'db_table': 'votos',
                'constraints': [models.UniqueConstraint(fields=('token', 'projeto'), name='voto_unico_por_token_projeto')],
            },
        ),
    ]
