# Generated by Django 5.2.17 on 2026-10-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoVotacao',
            fields=[
            ],
            options={
                'verbose_name': 'votação por edição',
                'verbose_name_plural': 'votação por edição',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cadastro.edicao',),
        ),
    ]
