# Generated by Django 5.2.17 on 2026-10-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0002_edicaovotacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacao',
            options={'permissions': [('operar_estacao', 'Pode operar a página da estação')], 'verbose_name': 'estação', 'verbose_name_plural': 'estações'},
        ),
    ]
