# Generated by Django 5.2.17 on 2026-10-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermissaoResultados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "permissão de resultados",
                "verbose_name_plural": "permissões de resultados",
                "permissions": [
                    (
                        "ver_resultados",
                        "Pode ver o ranking e os relatórios de resultados",
                    ),
                    ("exportar_visitantes", "Pode exportar a lista de visitantes"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
