# Generated by Django 5.2.17 on 2026-10-02 20:45

import cadastro.imagens
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=120)),
                (
                    "unidade",
                    models.CharField(
                        choices=[("fatec", "Fatec"), ("etec", "Etec")], max_length=5
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["unidade", "sigla"],
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("slug", models.SlugField(editable=False, max_length=70, unique=True)),
                ("resumo", models.CharField(blank=True, max_length=280)),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(3000)],
                    ),
                ),
                ("componente_origem", models.CharField(blank=True, max_length=120)),
                (
                    "capa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=cadastro.imagens.caminho_capa,
                        validators=[cadastro.imagens.validar_imagem],
                    ),
                ),
                (
                    "link_repositorio",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(schemes=["https"])
                        ],
                    ),
                ),
                (
                    "link_demo",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(schemes=["https"])
                        ],
                    ),
                ),
                (
                    "link_video",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(schemes=["https"])
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pre_cadastrado", "pré-cadastrado"),
                            ("em_revisao", "em revisão"),
                            ("publicado", "publicado"),
                            ("ajustes", "ajustes pedidos"),
                        ],
                        db_index=True,
                        default="pre_cadastrado",
                        editable=False,
                        max_length=14,
                    ),
                ),
                ("motivo_ajustes", models.TextField(blank=True)),
                ("representante_nome", models.CharField(max_length=120)),
                ("ra_hmac", models.CharField(editable=False, max_length=64)),
                (
                    "reivindicado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "token_edicao_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "token_edicao_gerado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "publicado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["turma", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Edicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60, unique=True)),
                ("data_evento", models.DateField()),
                ("ativa", models.BooleanField(default=False)),
                (
                    "prazo_edicao",
                    models.DateTimeField(
                        help_text="Depois disso, o link do grupo só mostra o conteúdo."
                    ),
                ),
                (
                    "peso_banca",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.70"), max_digits=3
                    ),
                ),
                (
                    "peso_publico",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.30"), max_digits=3
                    ),
                ),
                (
                    "votacao_aberta_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "votacao_encerrada_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("banca_conferida_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "edição",
                "verbose_name_plural": "edições",
                "ordering": ["-data_evento"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ativa", True)),
                        fields=("ativa",),
                        name="uma_edicao_ativa",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            django.db.models.lookups.Exact(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("peso_banca"),
                                    "+",
                                    models.F("peso_publico"),
                                ),
                                Decimal("1.00"),
                            ),
                            models.Q(("peso_banca__gte", 0), ("peso_publico__gte", 0)),
                        ),
                        name="pesos_somam_um",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("votacao_encerrada_em__isnull", True),
                            models.Q(
                                ("votacao_aberta_em__isnull", False),
                                (
                                    "votacao_encerrada_em__gte",
                                    models.F("votacao_aberta_em"),
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="encerramento_apos_abertura",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Integrante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Como aparece na página pública.", max_length=60
                    ),
                ),
                ("papel", models.CharField(blank=True, max_length=60)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes",
                        to="cadastro.projeto",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImagemProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.ImageField(
                        upload_to=cadastro.imagens.caminho_imagem,
                        validators=[cadastro.imagens.validar_imagem],
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo da imagem.",
                        max_length=120,
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="cadastro.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagem do projeto",
                "verbose_name_plural": "imagens do projeto",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_periodo",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "tipo_periodo",
                    models.CharField(
                        choices=[
                            ("semestre", "semestre"),
                            ("ano", "ano"),
                            ("modulo", "módulo"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manha", "manhã"),
                            ("tarde", "tarde"),
                            ("noite", "noite"),
                            ("integral", "integral"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="cadastro.curso",
                    ),
                ),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="cadastro.edicao",
                    ),
                ),
            ],
            options={
                "ordering": ["curso__sigla", "tipo_periodo", "numero_periodo"],
            },
        ),
        migrations.AddField(
            model_name="projeto",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projetos",
                to="cadastro.turma",
            ),
        ),
        migrations.AddConstraint(
            model_name="turma",
            constraint=models.UniqueConstraint(
                fields=("edicao", "curso", "numero_periodo", "tipo_periodo", "turno"),
                name="turma_unica_na_edicao",
            ),
        ),
        migrations.AddConstraint(
            model_name="turma",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("numero_periodo__gte", 1), ("numero_periodo__lte", 12)
                ),
                name="periodo_1_a_12",
            ),
        ),
    ]
