# Generated by Django 5.2.17 on 2026-10-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edicao",
            name="banca_conferida_em",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
